### ISSUE TITLE
文件已损坏

### ISSUE THREAD

**Issue by Morlin-279** [chu3/RunCat_Chinese#2]
懒人包解压拖到应用程序中提示“已损坏”，“隐私与安全性”无提示；
appstore下载覆盖安装中文包点击打开无反应；
macOS版本：13.6.7 (22G720)
望大佬解惑

**Comment by chu3** [comment]
不好意思这两天忙于找工作没法及时回复，关于该问题目前有一个解决办法：

1. App Store 下载最新 RunCat
2. git clone 或 下载 本项目，并解压获取 Contents 文件夹
3. 在应用程序中右键 RunCat  后点击 【显示包内容】 ，将获取到的 Contents 拖动到当前目录下 ，选择 【**合并** 】后启动程序即可。(合并 Contents )

关于懒人包启动显示“已损坏”这边也注意到了，稍后会发布修复好的版本，感谢支持🙏～

**Comment by chu3** [comment]
关于 懒人包 打开显示损坏问题，目前解决办法：

1. 启动程序显示 “‘RunCat’已损坏，无法打开。” 后，前往 【系统设置...】- 【隐私与安全性】- 【安全性】- 找到 “已阻止使用‘RunCat’，因为来自身份不明的开发者。” 点击 【仍要打开】即可。

再次感谢支持，后续有任何问题随时留言～～～ ❤️
